w-13216730 convert to valkyr
mulesoft/cluster-ssl-app pull request #8
Opened 2023-05-22 23:31 UTC by HONTAKYU

2023-06-02 00:45 UTC, diegostrubolini requested changes

2023-06-02 00:45 UTC, diegostrubolini commented on valkyr.yaml
> +product: pce
I think by default the slackChannel will be the product + "-bot" so I think we need to override it: https://github.com/mulesoft/onprem-config-api/blob/master/valkyr.yaml#L9

2023-06-02 00:45 UTC, diegostrubolini commented on images/hook/Dockerfile
> +FROM artifacts.msap.io/mulesoft/core-paas-base-image-ubuntu:v5.2.24@sha256:0be2945940a7a7ee25cc978a629d1dbce039050eb4f140a637713894cadca87a
Any reason not to point to the latest?

2023-06-02 17:29 UTC, HONTAKYU commented on valkyr.yaml
> +product: pce
Done

2023-06-02 17:54 UTC, HONTAKYU commented on images/hook/Dockerfile
> +FROM artifacts.msap.io/mulesoft/core-paas-base-image-ubuntu:v5.2.24@sha256:0be2945940a7a7ee25cc978a629d1dbce039050eb4f140a637713894cadca87a
I think it's a while since this change was made, updated to the latest

2023-06-09 19:49 UTC, fberckemeyer reviewed
@HONTAKYU, it would be useful to see a passing anypoint build that uses the code from this PR before the PR gets merged. This is the standard pattern for any service we use in anypoint.

So for example ...
https://jenkins.build.msap.io/job/PCE/job/anypoint-components/job/gravity-apps/job/cluster-ssl-app-new/job/PR-8/7/artifact/valkyr-manifest.yaml/*view*/
... update the spec in anypoint to use 4.0.0-2.w-13216730, regenerate the manifest and try to get a passing build.

2023-06-12 14:35 UTC, alejandrorascovan commented on Makefile
Who's calling the Makefile now that the repo is built with Valkyr?

2023-06-14 17:05 UTC, HONTAKYU commented
> @HONTAKYU, it would be useful to see a passing anypoint build that uses the code from this PR before the PR gets merged. This is the standard pattern for any service we use in anypoint.
> 
> So for example ... https://jenkins.build.msap.io/job/PCE/job/anypoint-components/job/gravity-apps/job/cluster-ssl-app-new/job/PR-8/7/artifact/valkyr-manifest.yaml/*view*/ ... update the spec in anypoint to use 4.0.0-2.w-13216730, regenerate the manifest and try to get a passing build.

Here we go: https://jenkins.build.msap.io/job/PCE/job/anypoint/job/PR-3820/17

2023-06-14 17:06 UTC, HONTAKYU commented on Makefile
Removed

2023-06-16 17:06 UTC, merged